### ISSUE TITLE
Test support for 4.1 -> Minor fixes

### ISSUE THREAD

**Issue by sarahjcotton** [catalyst/moodle-tool_heartbeat#127]
Fixed a few errors plus moodle-ci codechecker and phpdoc warnings.

Tested against:
• docker-dev local-integration (Ubuntu 22.04.1 LTS)
• mysql 8.0.31
• postgres (14.0 (Debian 14.0-1.pgdg110+1))
• php 8.0.25

**Comment by golenkovm** [comment]
It looks like this has been fixed in #128 
Closing as finished
Cheers
