### ISSUE TITLE
Protect against invalid tasks

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#134]
Under some as yet unknown conditions the croncheck page returns a html 404 error 

Coding error detected, it must be fixed by a programmer: Missing argument 1 for deadline_task::__construct

This page should always return a valid icinga status format even if it explodes for various reasons

**Comment by matthewhilton** [comment]
No sure of the example you gave, but I can recreate something which is along the same lines. E.g. if you insert an adhoc task with a class that does not exist, or modify `mdl_task_scheduled` to a class that does not exist you get debugging messages in croncheck.php:

```
<div class="notifytiny debuggingmessage" data-rel="debugging">Failed to load task: \core\task\fake<ul style="text-align: left" data-rel="backtrace"><li>line 291 of /lib/classes/task/manager.php: call to debugging()</li><li>line 429 of /lib/classes/task/manager.php: call to core\task\manager::scheduled_task_from_record()</li><li>line 224 of /admin/tool/heartbeat/croncheck.php: call to core\task\manager::get_all_scheduled_tasks()</li></ul></div>CRITICAL: Moodle task faildelay > 600 mins
```

**Comment by matthewhilton** [comment]
I assume the error `Missing argument 1 for deadline_task::__construct` is along the same lines e.g. \core\task\manager::get_tasks() failing to construct the task
