### ISSUE TITLE
Show details of the failing cron when only cron is failing

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#137]
If you have a single cron task failing rather than showing a generic 'cron is busted' in the summary, show the basic details of the task in the summary so that it doesn't mask the real issue

This may mean that that we need to manually check the tasks like we used to (code still exists) and suppress the core cron checks in the check api

Tests:
* [ ] many tasks are failing
* [ ] other checks are failing and tasks are failing
* [ ] some checks are warning but tasks are error / critical
* [ ] tasks are warning but checks are error / critical

**Comment by matthewhilton** [comment]
From what I read, are you saying that if for e.g. 1 adhoc task is broken, instead of just saying `adhoc task faildelay > ...`, instead say `task xyz faildelay > ..., here is the last log: ...`

Is that what you mean ?

**Comment by brendanheywood** [comment]
Here is an example of a site which is alerting:

```
CRITICAL: Moodle task faildelay > 600 mins
```

The problem is at a glance we have no idea what the actual issue is. The details are in the detail section but I want to move it up a level so it's more obvious.
eg:
```
CRITICAL: SCHEDULED TASK: core\task\h5p_clean_orphaned_records_task (Unused H5P files cleanup) Delay: 86400
```

If there are multiple things wrong then either show to most wrong one, or the first one, or we could go back to what it was before but maybe something like this showing the extend of the issue
```
CRITICAL: 12 Moodle tasks with faildelay > 600 mins
```
