### ISSUE TITLE
Improve consistency in output

### ISSUE THREAD

**Issue by matthewhilton** [catalyst/moodle-tool_heartbeat#150]
Right now the formatting of the `croncheck.php` is all over the place. The script is split into 'blocks', e.g. check if cron enabled, check adhoc/scheduled tasks, check check API. If any of these blocks reports a warning/error, it exits early.

This can lead to a situation where a long failing adhoc task masks any check API errors (which could be serious, e.g. objectfs connection failed)

The new format would look roughly like:

```
[Nagios status]: [Summary of ALL errors]
* [Error 1 title]
    [Error 1 details]
* [Error 2 title]
    [Error 2 details]
...
```
For example,
```
CRITICAL: Check API reported result errors:
* Dataflows
    HR Import: Run 16200 - aborted
    Details: https://test.com/report/status/index.php?detail=tool_dataflows_dataflow_runs
    https://test.com/admin/tool/dataflows/index.php
* Forced caching status
    Forced cache configuration is NOT active.
    Details: https://test.com/report/status/index.php?detail=tool_forcedcache_enabled
    https://test.com/admin/tool/forcedcache/index.php
* Task latency check
    Task \totara_core\task\tool_totara_sync_task has not run within the configured
    latency threshold: 2.
    Details: https://test.com/report/status/index.php?detail=tool_heartbeat_tasklatencycheck
* Task faildelay
    8 task(s) failing
    Fail delay: 1 day - tool_dataprivacy\task\process_data_request_task ID = 4
    Fail delay: 1 day - tool_dataprivacy\task\process_data_request_task ID = 5
    Fail delay: 1 day - tool_dataprivacy\task\process_data_request_task ID = 6

 (Checked Oct 10 13:00:50)
```

IMO the cleanest way to do this would be:

1. Fork this plugin for MOODLE_39_STABLE so we can assume check API exists and we don't have to care about legacy cron
2. Each of the errors are simply check results (scheduled and adhoc tasks are check classes, so we don't need to check these specifically)
3. Format these nicely and add the extra bit of logic to work out the nagios status and summary

Things to be mindful of though:
-  the only potential gotcha which that we'd have to double check (no pun) is that the check api was added and then various checks were added later than 3.9
- If the check API explodes (for e.g. bad plugin installed) it should report a critical with a clear message saying that this is masking real issues and should be fixed asap

**Comment by matthewhilton** [comment]
Looks like there is no check API for failing scheduled tasks. Probably is something that should be in core, but for the time being we can likely just add it as one of the checks inside heartbeat

**Comment by brendanheywood** [comment]
> Looks like there is no check API for failing scheduled tasks

yeah add it as a check here nd when we land it in core we'll branch again so we don't double up

**Comment by matthewhilton** [comment]
Re scheduled task check class, turns out it is part of the core check class:

https://github.com/moodle/moodle/blob/769c67045fe65c3e00ecad32b7639cb5acf13d88/admin/tool/task/classes/check/maxfaildelay.php#L64

Must have been editing the wrong db locally :see_no_evil:
