### ISSUE TITLE
Latest version causes upgrade to core version breaking sites.

### ISSUE THREAD

**Issue by marcusboon** [catalyst/moodle-tool_heartbeat#156]
In the latest [db/upgrade.php](https://github.com/catalyst/moodle-tool_heartbeat/blob/master/db/upgrade.php#L37), there seems to be a reference to `upgrade_main_savepoint()` instead of `upgrade_plugin_savepoint()`

**Comment by brendanheywood** [comment]
@matthewhilton just adding you here to double check things and make sure this ends up on the new stable branch as well

**Comment by matthewhilton** [comment]
Confirming the fix was cherry picked to the new stable branch https://github.com/catalyst/moodle-tool_heartbeat/pull/158/commits
