### ISSUE TITLE
Allow ignoring the "forcelogin" config option

### ISSUE THREAD

**Issue by Stickiler** [catalyst/moodle-tool_heartbeat#19]
Currently we're using Moodle for a project, however we have a requirement to force anyone to login before they can access the site. This causes our heartbeat to fail however, because this plugin uses the "require_login()" method which attempts to redirect to the login page, however a redirect is marked as a failure by the AWS health checks.

It would be excellent if we could have a configuration option to turn off the require_login check, to support more use cases.

**Comment by brendanheywood** [comment]
This doesn't make any sense, this plugin doesn't use require_login() anywhere? We are using this in production with plenty of sites which require login. ie this is empty:

https://github.com/catalyst/moodle-tool_heartbeat/search?utf8=%E2%9C%93&q=require_login&type=

**Comment by Stickiler** [comment]
That's actually really curious, the code we have looks nothing like the code in this repo, so I'll need to investigate and see what's gone wrong. Apologies for wasting your time.

**Comment by brendanheywood** [comment]
no dramas! ::
