### ISSUE TITLE
Allow disabling of the "ad hoc task queue" alert.

### ISSUE THREAD

**Issue by jhutch1** [catalyst/moodle-tool_heartbeat#191]

**Comment by brendanheywood** [comment]
This one is appearing as UNKNOWN when it is actually an INFO, so this should not come through at all

* UNKNOWN Ad hoc task queue: Ad hoc task queue has 293 tasks

**Comment by jhutch1** [comment]
I use Nagios to search the croncheck page for the word "OK", so as long as "OK" still appears when there's stuff in the ad hoc task queue I'm happy.

**Comment by brendanheywood** [comment]
This should have already been fixed by https://github.com/catalyst/moodle-tool_heartbeat/pull/194 which landed 2 weeks ago so closing this. If its still an issue on the latest commit then please reopen
