### ISSUE TITLE
Issue with unit tests and error log - this is expected just tell the tests to expect it (weird its not failing in plugin ci)

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#203]
Moodle 4.1.14+ (Build: 20241108), 6f07919b5f7ed20cd90c08ef90bb2117a1ad2839
Php: 8.0.30, pgsql: 12.20 (Debian 12.20-1.pgdg120+1), OS: Linux 6.5.0-1025-azure x86_64
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

.................Heartbeat error log test Thursday, 14 November 2024, 12:13 PM, next test expected in 1 min
.Heartbeat error log test Thursday, 14 November 2024, 12:13 PM, next test expected in 1 min
..                                              20 / 20 (100%)

Time: 00:01.876, Memory: 66.50 MB

OK (20 tests, 32 assertions)

**Comment by matthewhilton** [comment]
I think this is a dual issue:

1. The error log probably shouldn't be output during unit tests (we dont test for it we just care about the values it sets)
3. Using time() in tests - I thought I could get away with using less than or equal to, but I think this is causing it to fail in slower envs. Will refactor a bit to be deterministic.
