### ISSUE TITLE
Use of undefined constant CLI_SCRIPT

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-tool_heartbeat#48]
PHP Notice:  Use of undefined constant CLI_SCRIPT - assumed 'CLI_SCRIPT' in tool/heartbeat/index.php on line 47

_if (!defined(CLI_SCRIPT))_ should probably be _if (!defined('CLI_SCRIPT'))_

Version 2019031900

**Comment by brendanheywood** [comment]
thanks @ewallah and @sebastianberm
