### ISSUE TITLE
Version for Moodle 3.8, 3.7, 3.6 ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [catalyst/moodle-tool_heartbeat#68]
According to the stats tab of https://moodle.org/plugins/stats.php?plugin=tool_heartbeat, half of all Moodle users of this plugin have a Moodle 3.5 branch, plus 42 Moodle 3.6, 52 Moodle 3.7 and 4 Moodle 3.8 branches.

Can you please check your plugin for these Moodle branches and (if OK) mark the plugin as supported for them ?

Thanks in advance.

**Comment by Urpokarhu1** [comment]
Hello,

Will there be support for Moodle 3.6, 3.7 and 3.8?

**Comment by ernani** [comment]
Also wondering on 3.9 and 3.1x

**Comment by germanvaleroelizondo** [comment]
In 2018 there were versions for Moodle branches up to 3.8.
But more than 500 Moodle 3.9 sites were using it according to https://moodle.org/plugins/tool_heartbeat/versions

**Comment by Urpokarhu1** [comment]
Hello,

Will you support version 3.9 and upwards?
