### ISSUE TITLE
"IP Blocking Configuration" not working as expected

### ISSUE THREAD

**Issue by rlorenzo** [catalyst/moodle-tool_heartbeat#94]
The setting "IP Blocking Configuration" says that it is a list of "safe IP addresses for the heartbeat to respond to"... however, this setting is only used in iplock.php, and that file is not included nor the function validate_ip_against_config() used anywhere else.

How does the "IP Blocking Configuration" work to restrict the IPs that the endpoints like index.php, adminloginchecker.php, compresscheck.php, buffercheck.php, compresscheck.php, notbuffered.php, progress.php,  sessionone.php, sessiontwo.php, and upload.php?

It seems that all these endpoints can be called by anyone, even non-logged-in users.

**Comment by jaypha** [comment]
A lot of these endpoints include the iplock file. Not all of them though. Will refactor a little.
