### ISSUE TITLE
Fully "turn on" check api checks, ie critical checks are critical in heartbeat

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#97]
https://github.com/catalyst/moodle-tool_heartbeat/blob/master/croncheck.php#L308-L311

- [x] Criticals as criticals
- [x] Errors as criticals (can be MUCH noiser due to adhoc task fails)

**Comment by Peterburnett** [comment]
First task will be addressed in #98 , Errors to follow

**Comment by Peterburnett** [comment]
This has been implemented as configuration for how checks are exposed in #118 . Closing this one off.
